### ISSUE TITLE
Flash Boiler fuel slot inaccessible

### ISSUE THREAD

**Issue by ZeekDaGeek** [Esteemed-Innovation/Esteemed-Innovation#160]
Forge version: 10.13.2.1236
Mod version: 0.27.1
Other mods: http://tinyurl.com/wwpack

The fuel slot in Flash Boilers seems to be inaccessible to normal means when extracting.

In the event of pressure emergencies I'm attempting to pull all fuel out of Flash Boilers but it seems like you cannot actually pull the fuel out. I've tried from the side, bottom and top.

A nice alternative would be an item that allows redstone control on boilers. Maybe some sort of air flow valve or something to allow more automation and less explosions or maintenance.

**Comment by elifoster** [comment]
07eff13a09eb00a2dc7b4de5adeb4ac6fe1cee40
