### ISSUE TITLE
Archimedes ships + Exo Suit crash

### ISSUE THREAD

**Issue by PsionicArchon** [Esteemed-Innovation/Esteemed-Innovation#164]
Attempting to right click a ship's helm while wearing the exo suit causes the client to crash.

I'm also getting a strange zoom out effect while equipping the armor, not entirely sure why my fov changes while wearing the armor.

Crash log: http://pastebin.com/vKQTT4HJ

**Comment by xbony2** [comment]
@PsionicArchon can you re-test this?

**Comment by elifoster** [comment]
Archimedes' Ships does not exist past Minecraft 1.7.
