### ISSUE TITLE
Armor rendering breaks with Smart Moving

### ISSUE THREAD

**Issue by asiekierka** [Esteemed-Innovation/Esteemed-Innovation#259]
Still assumes the default player model is present. Perhaps we need less assumptions?

**Comment by Barhandar** [comment]
It breaks even more hilariously with MineLP, like any other custom-model armor. It looks like an invisible ghost midget wearing it, presumably because of proportion changes. 

Can a model-render like this be overriden by a different mod or resourcepack, even?

**Comment by EEvP** [comment]
I doubt this issue could be over ridden by another mod.  It's an issue with smart-moving's APIs and happens with all custom 3D armor mods.  It bothers me too.

**Comment by elifoster** [comment]
Smart Moving does not exist past Minecraft 1.8.
