### ISSUE TITLE
Unable to start world, kicked back to main menu with Mekanism error

### ISSUE THREAD

**Issue by DeusExNihil** [Esteemed-Innovation/Esteemed-Innovation#298]
http://pastebin.com/1cyBStqx

I began getting this error after adding a batch of mods to my modpack. Removing Steam Power fixed said error. I'm not an expert by any means, so I've no idea what is causing this, other than a conflict with Mekanism.

**Comment by elifoster** [comment]
Have you reported this to the Mekanism developers?

**Comment by DeusExNihil** [comment]
Yes, although at the time I did not know for sure it was caused by this mod. I'm going to update the post now

**Comment by elifoster** [comment]
It still isn't confirmed that we are causing the issues.

**Comment by hlaaftana** [comment]
https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/recipe/inputs/MachineInput.java#L32
Most likely Mekanism issue.

**Comment by Tsyklop** [comment]
I recreate the configuration file FSP and everything was fine.

**Comment by hlaaftana** [comment]
close close close close

**Comment by elifoster** [comment]
Why was this closed? The bug isn't fixed, and we don't know for sure that it's mekanisms fault

**Comment by hlaaftana** [comment]
It isn't confirmed, and he said removing the config fixed it...
He probably messed up something in the configs.

**Comment by elifoster** [comment]
Removing what from the configs?...

**Comment by Tsyklop** [comment]
@elifoster Removed config file FSP, and everything was fine.

**Comment by elifoster** [comment]
Can you paste the old config file?

**Comment by Tsyklop** [comment]
@elifoster http://pastebin.com/caapRiXz

**Comment by elifoster** [comment]
I don't see anything wrong with it, but if all it was was a bad config, closing.

**Comment by Tsyklop** [comment]
I found out because of that crash ...
If the config change everything value at false it will crash.

    B:"Enable Copper Ore. This does not enable world generation of the ore, but will disable it if false."=true
    B:"Enable Poor Zinc Ore. This does not enable world generation of the ore, but will disable it if false."=true
    B:"Enable Zinc Ore. This does not enable world generation of the ore, but will disable it if false."=true

**Comment by hlaaftana** [comment]
Don't get what you mean. If you type in anything other than "true" or "false" in there, it will not work.

**Comment by elifoster** [comment]
@hlaaftana For what it's worth, despite this being a completely dead issue, that's actually not true. Look at Boolean#parseBoolean; it checks if it is "true" with any casing, and not null. Otherwise it assumes false.
