### ISSUE TITLE
Compatibility error with the Witching Gadgets.

### ISSUE THREAD

**Issue by Offertorium** [Esteemed-Innovation/Esteemed-Innovation#316]
Hi there,

i have an Error on start up my priv. Modpack.  It seems a compatibility error with the Mod Witching Gadgets. Log see here: Error: http://pastebin.com/Y9dSnFA0 

What does this error and can this crash my Game?

My Java Version:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

My OS is Windows 7

Thank you for your help and your amazing Mod

Bye

**Comment by xbony2** [comment]
Can we have the full log?

**Comment by Offertorium** [comment]
Of Course, here it is: http://pastebin.com/dqTs12G2

**Comment by xbony2** [comment]
Test without Optifine.

**Comment by Offertorium** [comment]
Hi, without Optifine I have the same error.

**Comment by elifoster** [comment]
Can we have the full log without Optifine installed?

**Comment by Offertorium** [comment]
Hi, thanks for your help. Here ist he Log: http://pastebin.com/FQH4WHyu

**Comment by elifoster** [comment]
Paging @BluSunrize

**Comment by BluSunrize** [comment]
Doesn't seem to actually crash though does it? It's an NPE that's being caught, the instance seems to finish loading.

On a different note though, why check the clientsided dimension ID in the getIcon method? I realize this is to make ores look like endstone or netherrack, but this way that happens to overworld ores brought into the nether. Doesn't make a lot of sense to me, tbh =P

**Comment by elifoster** [comment]
It's still an error...

And yeah, that is a good point. At the time I added that feature, it made sense, but looking back now, I guess I should set the icon based on the dimension that it was generated in.

**Comment by BluSunrize** [comment]
If it's a caught error, noone cares unless it spams the log constantly And this is one that happens once as WG tries to analyze the ore's texture to generate the cluster, but it only does it once.

**Comment by elifoster** [comment]
Since this was a getIcon thing, this is no longer an issue. Furthermore, I addressed the issue BluSunrize brought up about ore world variants a long while ago in 386f15ec177e6c393e3973c09eb9ab4431cc2fb7
