### ISSUE TITLE
Steam Heaters change furnace recipe priority (maybe?)

### ISSUE THREAD

**Issue by Zsashas** [Esteemed-Innovation/Esteemed-Innovation#336]
I have JadedTweaks which adds a recipe for one Acacia Log to smelt into four charcoal (along with varying amounts for other logs). The vanilla recipe is left alone, however, for some reason.

When using a steam heater to power the furnace, the Acacia log smelts into 1 charcoal, following the vanilla recipe.

When using the furnace's fuel slot, the logs smelt into four charcoal each, following the new recipe.

I have no idea why this would be happening. Why does it matter how the furnace is fueled? Does the steam heater somehow have a separate recipe handler or something?

Additional testing: it seems that, the first time after the world is loaded, if the heater is used, it uses the 1:1 recipe. If the first use after loading was with fuel, it uses the 1:4 recipe. This makes even less sense to me.

**Comment by elifoster** [comment]
I can't see why this would be happening. It gets its recipes directly from Minecraft's FurnaceRecipes class.

``` java
FurnaceRecipes.smelting().getSmeltingResult(furnace.getStackInSlot(0));
```

**Comment by elifoster** [comment]
Pretty certain this is because JadedTweaks doesn't remove the old recipes.

**Comment by ghost** [comment]
This issue was fixed in upstream in JadedPacks/JadedTweaks.

@elifoster May want to close this now.
