### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Esteemed-Innovation#372]
* [x] License should be formatted in markdown. Seriously.
* [x] We either need to choose a different license that does not allow for sharing without our consent, or remove all the "Ask us before putting it in a modpack" crap from all the threads. @xbony2 @Strikingwolf @Lance5057 @Divineaspect  what do y'all think? I personally would rather do the latter, as this has always been an open source project.

Consent:

* [x] @Flaxbeard
* [x] @Zenith-One 
* [x] @Mrkwtkr
* [x] @Gholuk 
* [x] @Kris1432 
* [x] @Ghoughpteighbteau 
* [x] @Vexatos 
* [x] @hlaaftana 
* [ ] @Juput 
* [x] @vidaj
* [x] @kenzierocks 
* [x] @PaperTriangle 
* [x] @ChrisLangley 
* [x] @hurr1k4ne 
* [x] @allaryin 
* [x] @Strikingwolf 
* [x] @jaredlll08 
* [x] @ganymedes01 
* [ ] @al-myr 
* [x] @Lance5057 
* [x] @dmillerw 
* [x] @xbony2 
* [x] @elifoster
* ~~@devFozgul~~ This user's commits are not going to be in any future versions of FSP at this time. If they actually follow through with resubmitting their PRs to the 1.9 branch, maybe.
* [x] @Adaptivity 
* [ ] @mymagadsl 
* [x] @CodeAlchemist-T

**Comment by xbony2** [comment]
Public Domain or riot.

**Comment by Strikingwolf** [comment]
I agree, although I do believe that courtesy is ask before, but not required would be the preferred way to put it. That is if you don't want to just remove the requirement altogether

**Comment by Lance5057** [comment]
I'm for removing the "ask first " bit, to me it always sounds slightly pretentious.
As for license I'd just suggest one that forbids commercial use or add in use for monetary gain isn't allowed. Mostly because I hate item selling servers.

**Comment by elifoster** [comment]
@xbony2 eh
@Strikingwolf I think a better way to say that would be "Let us know if you are using it in a modpack!" which we already state in the thread :stuck_out_tongue:

**Comment by xbony2** [comment]
I'm not agreeing to any license that isn't open as possible. Dicky server owner don't really listen to licenses; a restrictive license over tiny software like this is just protection to artificially make yourself feel better.

**Comment by Strikingwolf** [comment]
@elifoster that's what I meant, I just typed that at 2 AM in the morning :laughing:

**Comment by elifoster** [comment]
@xbony2 how about we agree to disagree, and settle on a middle ground, like the CC BY 4.0 license?

@Lance5057 I agree about the servers, but modpack developers should definitely be allowed to profit (like through curse forge rewards). If that wasn't a thing, I would be all for an NC license.

**Comment by Strikingwolf** [comment]
I would do MIT license with at the top an added pointer to the MC Eula, as that forbids item-selling servers and such

**Comment by Divineaspect** [comment]
MIT license seems to meet all our preferences.

I'd suggest adding a note that we like to hear about it's inclusion, and the MC eula, not to the license, but to pages the mod is connected to.

**Comment by xbony2** [comment]
MIT has [it's own issues](http://forum.freegamedev.net/viewtopic.php?f=7&t=4328).

**Comment by elifoster** [comment]
Xbony, most of that thread is people complaining about public domain licenses.

**Comment by xbony2** [comment]
It's the first part- the vagueness of "substantial portions".

**Comment by elifoster** [comment]
@xbony2 http://programmers.stackexchange.com/questions/178486/what-exactly-does-the-condition-in-the-mit-license-imply That doesn't seem to really make any sort of difference.

**Comment by elifoster** [comment]
@xbony2 I don't really want to go public domain. I'm cool with [MIT](http://choosealicense.com/licenses/mit/) or [Apache](http://choosealicense.com/licenses/apache-2.0/) though.

**Comment by xbony2** [comment]
If you want to it to be open, you might as well make it open and not just "mostly open".

**Comment by elifoster** [comment]
I can't find anything to support *not* going with CC0, so I'm fine with that. We do have to get consent from all contributors, which will be fun in the curious case of flaxbeard

**Comment by elifoster** [comment]
So, we need consent from all the contributors to change the license from GPL v2 to CC0. You can read a summary of it [here](https://creativecommons.org/publicdomain/zero/1.0/).

* [ ] @Flaxbeard
* [ ] @Zenith-One 
* [ ] @Mrkwtkr
* [ ] @Gholuk 
* [ ] @Kris1432 
* [ ] @Ghoughpteighbteau 
* [ ] @mymagadsl 
* [ ] @Vexatos 
* [ ] @L1b3r4t0r 
* [ ] @hlaaftana 
* [ ] @Juput 
* [ ] @vidaj
* [ ] @kenzierocks 
* [ ] @PaperTriangle 
* [ ] @ChrisLangley 
* [ ] @hurr1k4ne 
* [ ] @allaryin 
* [ ] @Strikingwolf 
* [ ] @jaredlll08 
* [ ] @ganymedes01 
* [ ] @al-myr 
* [ ] @Lance5057 
* [ ] @dmillerw 
* [ ] @xbony2 
* [ ] @elifoster

I know this is annoying. Sorry :P

**Comment by ChrisLangley** [comment]
Not sure what you'd need me to do, you have my consent of course, let me
know if you need me to do something more specific.

**Comment by hurr1k4ne** [comment]
I'm okay with the change in license.

Hurr1k4ne
Am 31.03.2016 7:54 nachm. schrieb "Eli Clemente Gordillo Foster" <
notifications@github.com>:

**Comment by xbony2** [comment]
Yes.

**Comment by Mrkwtkr** [comment]
Yes

**Comment by ganymedes01** [comment]
I don't even remember ever contributing to this. So yes, you have my permission to do whatever you want.

**Comment by Ghoughpteighbteau** [comment]
I remember contributing a small bit, I relinquish that small bit to you guys. Do what you think is right!

**Comment by Lance5057** [comment]
I'll allow it

**Comment by kenzierocks** [comment]
I'm fine with it.

**Comment by Zenith-One** [comment]
Fine by me.

**Comment by allaryin** [comment]
Generally speaking, creative commons isn't appropriate for software. Most permissive open source mods use Apache.

**Comment by xbony2** [comment]
~~~
May I apply CC0 to computer software? If so, is there a recommended implementation?

Yes, CC0 is suitable for dedicating your copyright and related rights in computer software to the public domain, to the fullest extent possible under law. Unlike CC licenses, which should not be used for software, CC0 is compatible with many software licenses, including the GPL.
~~~
- CC website

**Comment by allaryin** [comment]
https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by xbony2** [comment]
We're talking CC0 which is different.
~~~
Also, the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.
~~~

**Comment by allaryin** [comment]
Oh. CC0. Sorry, just saw what looked like one of the classic blunders. Carry on then ;)

**Comment by hlaaftana** [comment]
idk what i did but sure

**Comment by vidaj** [comment]
Go right ahead.

**Comment by jaredlll08** [comment]
Don't care what license you chooe, but go ahead

**Comment by xbony2** [comment]
Who are we missing?

**Comment by Kris1432** [comment]
Hey, sorry, I approve.

**Comment by xbony2** [comment]
Let's see....
- ~~Flaxbeard~~
- @dmillerw ?
- ~~Gholuk~~
- @devFozgul ?
- @al-myr ?
- ~~Vexatos~~
- ~~Adaptivity~~
- @mymagadsl ?
- ~~Strikingwolf~~
- ~~CodeAlchemist-T~~
- ~~probably don't need waffle-iron~~
- @ChrisLangley ?
- @PaperTriangle ?
- @Juput ?

**Comment by labpaw** [comment]
@xbony2 you can relicense my contributions to any license. My contribution belongs to you and Esteemed Innovation team.

**Comment by elifoster** [comment]
Flax and Striking gave the ok on IRC. Waffle-iron is a bot.

**Comment by xadaemon** [comment]
You have express consent from me to change the licence to any you may want as long as it stays open source software.

**Comment by Gholuk** [comment]
I am fine with it. Open Source!

**Comment by Vexatos** [comment]
I only contributed parts of a lang file. License it however you want, although I would prefer it to stay open-source.

**Comment by dmillerw** [comment]
You have express consent from me to change the licence to any you may want as long as it stays open source software.

**Comment by PaperTriangle** [comment]
I'm fine with it.
