### ISSUE TITLE
TerraFirmaCraft water support

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Esteemed-Innovation#378]
The Archimedes Screw can pick up the TFC water, but the Boiler does not use it. This has been reported on the MCF thread. Perhaps we could simply convert TFC water into normal water when input into the boiler? That seems to be the easiest way to do it

@xbony2 Do you want to deal with this?

**Comment by xbony2** [comment]
TFC support is awfully low priority. TFC and pretty much all other mods don't really mesh together...

**Comment by elifoster** [comment]
I was looking at the TFC forums earlier today, and it seemed like a lot of the TFC players also play FSP.

**Comment by elifoster** [comment]
TerraFirmaCraft does not exist past Minecraft 1.7. Furthermore, the 1.10 version of EI actually allows for a nice bridge mod to set the water value we use as of a1e117826f2d2fc8c00298cd0e77432c1118fcf4
