### ISSUE TITLE
Stone Grinder in need of blacklist capabilities

### ISSUE THREAD

**Issue by Nygmus** [Esteemed-Innovation/Esteemed-Innovation#420]
## Description
The Stone Grinder drill upgrade badly needs a config-level blacklist. In addition to worthless materials like Mana-Infused Metal (TE) and alloys (Tinker's Steel, Immersive Engineering Constantan, Tinker's Aluminum Brass), it's producing nuggets of rare ores like Ardite/Cobalt and expensive magical ones like Botania Terrasteel and Elementium.

## Base information
* Minecraft version: 1.7.10
* Flaxbeard's Steam Power version: 029.2

**Comment by elifoster** [comment]
I think another good solution might be to use the sneak key to disable upgrade functionality in general.

**Comment by Nygmus** [comment]
Possibly, but the problem isn't the grinder needing to be disabled; the problem is that the grinder is generating things that it really, really shouldn't be.

An interim solution might be to limit the stone grinder to producing nuggets of vanilla/FSP metals only; it's cross-mod interaction causing the problem.

**Comment by elifoster** [comment]
Oh yeah I think there should definitely be a config. I was just brainstorming.
