### ISSUE TITLE
Overclocker slows down or speeds up?

### ISSUE THREAD

**Issue by Shurik1236** [Esteemed-Innovation/Esteemed-Innovation#434]
"Overclocker" ускоряет или замедляет в 2,5 раза? / (Google) "Overclocker" speeds up or slows down in 2.5?
https://youtu.be/NiUawD3itZ0
- Minecraft version: 1.7.10
- Minecraft Forge version: 1566
- Flaxbeard's Steam Power version: 0.29.2

**Comment by elifoster** [comment]
Fixed by 424439b
