### ISSUE TITLE
Minetweaker & FSP

### ISSUE THREAD

**Issue by Omuck3** [Esteemed-Innovation/Esteemed-Innovation#437]
I am trying to add/remove crucible recipes with MineTweaker.  I have ModTweaker installed, as well.  My Minecraft version is 1.7.10, Forge version 10.13.4.1614.  My FSP version is 0.29.2, which I thought had MineTweaker integration.

The script I'm using is:

```
removeMeltRecipe(<Steamcraft:smashedOre>, "liquidIron");
mods.fsp.Crucible.addMelting(<Steamcraft:smashedOre>, "liquidIron", 5);
```

The removeMeltRecipe is from [here](https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/commit/17ce180413ac1151867cae66837a802bfff3333d).

Any help you could provide would be very appreciated.

**Comment by elifoster** [comment]
liquidIron is not a crucible liquid. The liquid names added by FSP are:
* `iron`
* `gold`
* `zinc`
* `copper`
* `brass`

as you can see [here](https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/blob/master/src/main/java/flaxbeard/steamcraft/SteamcraftRecipes.java#L41-L54)

**Comment by Omuck3** [comment]
The issue is with removeMeltRecipe

**Comment by elifoster** [comment]
First, you need to call it as mods.fsp.Crucible.removeMeltRecipe, not just removeMeltRecipe.

Second, you need to give it a liquid that exists (see my previous posts for the default ones; there are some more from cross mod integration but those are the main ones).

Third, might not be an issue, but smashedOre is a metadata item, so your recipes probably won't work as you expect unless you give it the proper metadata.

**Comment by Omuck3** [comment]
`mods.fsp.Crucible.removeMeltRecipe(iron);`

It says that there is "no such static member in mods.fsp.Crucibe.removeMeltRecipe" and that "any values not yet supported."

**Comment by elifoster** [comment]
If the error is exactly `no such static member in mods.fsp.Crucibe.removeMeltRecipe`, then it's likely you misspelled `Crucible`. You also forgot the first parameter which is an IItemStack IIRC. You also need to wrap `iron` in quotation marks, as it takes a String `"iron"`. I recommend taking a look at the docs, http://ftb.gamepedia.com/Using_MineTweaker_and_Flaxbeard's_Steam_Power, as well as looking into ZenScript and MineTweaker's usage.

**Comment by Omuck3** [comment]
Ok, thanks.  When I had it in quotations, I got this crazily long error.  I'll look at the spelling and see what happens.

**Comment by Omuck3** [comment]
Well, turns out I spelled `Crucible` correctly the first time around.  The error regarding the static member continues.  My code is currently:

```
mods.fsp.Crucible.removeMeltRecipe(<minecraft:iron_ore>, "iron");
mods.fsp.Crucible.addMelting(<Steamcraft:smashedOre>, "iron", 5);
```

**Comment by elifoster** [comment]
addMelting is not a function. There is addMeltRecipe, addOreMeltRecipe, and addToolMeltRecipe.

**Comment by Omuck3** [comment]
I fixed that line, but there's still an error about the static member in the first line.  Is there any way for me to fix it?

**Comment by Omuck3** [comment]
Just an update.  So I think I'm using all the correct code, yet it continues to simply not.  The third line is just me testing.
```

mods.fsp.Crucible.removeMeltRecipe(<Steamcraft:smashedOre>, "iron");
mods.fsp.Crucible.addMeltRecipe(<Steamcraft:smashedOre:13>, "iron", 5);
mods.fsp.Crucible.addOreMeltRecipe(<minecraft:iron_ore>, "iron", 5);
```

**Comment by elifoster** [comment]
What is the exact error, if any? Also, addOreMeltRecipe takes a string, not an itemstack (`mods.fsp.Crucible.addOreMeltRecipe("oreIron", "iron", 5);`)

**Comment by Omuck3** [comment]
```
[19:37:21] [Client thread/INFO]: [CHAT] ERROR: ?:1 > No such static member in mods.fsp.Crucible: removeMeltRecipe
[19:37:21] [Client thread/INFO]: [CHAT] ERROR: Error executing Cast Iron.zs: 1
[19:37:25] [Client thread/INFO]: [CHAT] Scripts reloaded
```

**Comment by elifoster** [comment]
Does this occur when you initially load the game/world, or are you using /mt reload? I specified in the changelog that /mt reload will not work.

**Comment by Omuck3** [comment]
Both.

**Comment by Omuck3** [comment]
Well, technically when I intially load.  I tested it with just FSP, Minetweaker, and Modtweaker.

**Comment by mallrat208** [comment]
So as an independent test, I made a new instance with the most recent version of Forge for 1.7.10, Minetweaker, and FSP
```
import mods.fsp.Crucible;

Crucible.removeMeltRecipe(<Steamcraft:smashedOre:0>, "iron");
```
And that works as you would expect

**Comment by Omuck3** [comment]
It's not working.  I just copied your code.

I got this:
[17:16:44] [Client thread/INFO]: [CHAT] ERROR: Cast Iron.zs:3 > No such static member in mods.fsp.Crucible: removeMeltRecipe
[17:16:44] [Client thread/INFO]: [CHAT] ERROR: Error executing Cast Iron.zs: 1

**Comment by Omuck3** [comment]
Ok, so I changed my forge version, and appears to work.  But I got the a "WARNING: 1 modifications were stuck" when I made a new world.  I did /mt reload to see what happened, and every time I got that warning with an increased number.

**Comment by elifoster** [comment]
Have you tried reinstalling FSP? I am seriously confused by this issue.

**Comment by Omuck3** [comment]
It's functioning now, but I'll try that in a little bit.

**Comment by Omuck3** [comment]
Well, it turns out that it continues to not work, with the same issue, in the modpack.  I've updated forge and FSP.  Still the same error.  And yet it works on vanilla.  Could it be some sort of mod conflict?

**Comment by elifoster** [comment]
I can't see why there would be, but I wouldn't rule out that possibility entirely just because of how little this makes sense...

**Comment by Omuck3** [comment]
Tried it with what I saw as the "core" mods of the pack.  Still didn't work, same error.  In the chat, it was under the initialization of Better Beginnings.  So I took that out, and the error persisted.  With just FSP, minetweaker, and modtweaker it didn't work.  The error is ```
[18:24:07] [Client thread/INFO]: [CHAT] ERROR: Cast Iron.zs:5 > No such static member in mods.fsp.Crucible: removeMeltRecipe
[18:24:07] [Client thread/INFO]: [CHAT] ERROR: Error executing Cast Iron.zs: 1
```

 My code:

```
import mods.fsp.Crucible;

val SmashedIron = <Steamcraft:smashedOre:0>;

mods.fsp.Crucible.removeMeltRecipe(<Steamcraft:smashedOre:0>, "iron");
mods.fsp.Crucible.addOreMeltRecipe("oreIron", "iron", 5);
mods.fsp.Crucible.addMeltRecipe(SmashedIron, "iron", 4);
```


Now I'm going to just try each mod one by one.  I'll update you if I find an answer.

Mod list: 
Better Beginnings
Block Properties
Buildcraft
Buildcraft Compat
FSP
IC2 Nuclear Control
IC2
Immersive Engineering
JourneyMap
Minetweaker
Minetweaker RecipeMaker
Modtweaker
Quadrum

**Comment by Omuck3** [comment]
**I HAVE DISCOVERED THE ISSUE.  IT'S MODTWEAKER!**

**Comment by elifoster** [comment]
Oh, that actually makes perfect sense. IIRC they have broken fsp integration. @jaredlll08

**Comment by mallrat208** [comment]
Success!

**Comment by Omuck3** [comment]
Hi again.  Would it be possible for me to have Modtweaker installed, but keep it from interfering with FSP?

**Comment by elifoster** [comment]
You'd have to decompile it and remove the fsp integration.

**Comment by Omuck3** [comment]
But didn't it drop FSP integration?

**Comment by jaredlll08** [comment]
I'm fairly sure that we removed FsP support,  like not just commenting it
out, like full on deleted it, so I doubt the problem is us

**Comment by Omuck3** [comment]
There's a folder for FSP in the modtweaker file.  If I delete that folder, would it fix the problem?

**Comment by elifoster** [comment]
It should. Try it and report back :smile:

**Comment by jaredlll08** [comment]
Also just checked, apparently I never removed it... According to github
anyway

**Comment by Omuck3** [comment]
If I delete the fsp folder I get an error:

`cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: modtweaker2/mods/fsp/Steamcraft`

**Comment by elifoster** [comment]
Ah yeah. You'll have to modify the other source files and remove all references of it. Or Jared could do that and push a new release of mt 😉

**Comment by Omuck3** [comment]
> Or Jared could do that and push a new release of mt

That would be nice. :) @jaredlll08

**Comment by Voidi** [comment]
Please test http://ci.tterrag.com/job/ModTweaker2/172/
