### ISSUE TITLE
Coal burning time, bugged?

### ISSUE THREAD

**Issue by Nezraddin** [Esteemed-Innovation/Esteemed-Innovation#438]
Hello.

I'm actually not really sure if that is a bug or is part of the "Flash Boiler now properly updates the heat countdown"-fix. But it kinda looks like a bug to me:

I have a system of 1 flashboiler, 8 steam tanks.
Before the update to the 0.29.1 version (modpack uses this version, but I tested the 0.29.2 version, too, same issue) dropping two charcoal with droppers inside raised it around 2~4%. 
With the new version it seems a single charcoal raises the steam-% by around 12~13% (~26% for two even while six furnace heaters were running). Which seems quiet a huge increase of how much steam you get (and I almost blew up my system, love the rupture disc!).

[edit]
After some more testing it seems, like the burn-timer stops (so the flame disappears) but the steam-% still goes up for another 5~6%.

**Comment by elifoster** [comment]
IIRC that fix was purely client side, so it's not related to this.

**Comment by elifoster** [comment]
Flash Boiler no longer exists in the next update.
